exercism/groovy

config.json, hello-world/Example.groovy, hello-world/HelloWorld.groovy, hello-world/HelloWorldTest.groovy
Addresses: https://github.com/exercism/todo/issues/33
=> Add Hello World exercise

config.json, exercises/phone-number/Example.groovy, exercises/phone-number/PhoneNumberSpec.groovy
Per [the most excellent documentation](https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#porting-an-exercise-to-another-language-track), I'm opening this Pull to call dibs and track an implementation of `phone-number` for Groovy.
=> Open Pull to implement `phone-number` exercise

docs/ABOUT.md, docs/INSTALLATION.md, docs/LEARNING.md, docs/RESOURCES.md, docs/TESTS.md
This is my little attempt to address/comment Issue #35 .
I'll start off by saying that the track documentation didn't seem to violate anything technical in the [guidelines here](https://github.com/exercism/exercism.io/blob/master/docs/writing-track-documentation.md).   The files were present, and didn't reference any images (so it couldn't mis-reference them 😃 ).
However, the current instructions seemed more involved than those of other tracks, and I decided to give some edits a whirl.  I've tried to remove references to IDEs in favor of limiting instructions to getting the tools and using the command line to execute the tests.
All that said, whether folks think the edits are an improvement or not— I'm happy to do some more proof to try to make sure we feel good about #35.
Hope this finds …
=> Issue #35 : Proposed edits to track documentation

exercises/hello-world/Example.groovy, exercises/hello-world/HelloWorld.groovy, exercises/hello-world/HelloWorldSpec.groovy
As discussed in [`x-common` Pull #544](https://github.com/exercism/x-common/pull/544) .  This lonely maintainer could use a second set of eyes.
Please refrain from merging this Pull until the date mentioned in [`x-common` #544](https://github.com/exercism/x-common/pull/544) (as of this writing, "2016-02-20 00:01 UTC +-1 day").
=> hello-world: Change to always expect "Hello, World!"

docs/ABOUT.md, docs/LEARNING.md, docs/RESOURCES.md
In this Pull I've attempted to correct my own sins, mainly
* fixing grammatical and proofing errors in the documentation changes I wrote and
* adding to the learning resources Groovy Koans
* which I'd had in my notes to add to the docs, but neglected to do so
* (I'm not *wholly* sure it belongs in the same Pull, and would welcome feedback.)
=> Update track documentation

config.json
This is a work-in-progress Pull to update exercise difficulties in `config.json`, part of our effort to move Issue #27 forward.
=> Update config.json difficulty fields

docs/ABOUT.md
Updates ABOUT.md formatting as described in [exercism/meta#85](https://github.com/exercism/meta/issues/85)
=> Updates ABOUT.md formatting for Nextercism

config.json
As @kytrinyx mentioned in discussion for #27 there were no topics for exercises.
This PR is an attempt to suggest suitable and general ones which are commonly used in other language tracks
=> Adds exercise topics to configuration file

exercises/difference-of-squares/Squares.groovy, exercises/hamming/Hamming.groovy, exercises/leap/Year.groovy, exercises/nth-prime/Prime.groovy, exercises/phone-number/PhoneNumber.groovy, exercises/raindrops/Raindrops.groovy, exercises/rna-transcription/Complement.groovy, exercises/robot-name/Robot.groovy
=> Adds missing placeholder class files

docs/INSTALLATION.md, docs/RESOURCES.md
Adds some small improvements for the documentation
Ref: #9
=> Improves installation and resources docs

CONTRIBUTING.md, README.md
Hopefully resolves #7 
I've tried to keep the CONTRIBUTING.md short
=> Adds CONTRIBUTING.md for the track

config.json, exercises/two-fer/Example.groovy, exercises/two-fer/README.md, exercises/two-fer/TwoFer.groovy, exercises/two-fer/TwoFerSpec.groovy
Implementation for `two-fer` for the issue #70
=> Adds two-fer implementation

config.json
See exercism/problem-specifications#884
=> config: replace "math" topic with "mathematics"

config.json, exercises/scrabble-score/Example.groovy, exercises/scrabble-score/README.md, exercises/scrabble-score/ScrabbleScore.groovy, exercises/scrabble-score/ScrabbleScoreSpec.groovy
Includes tests, example, readme.
Issue: #78
=> scrabble-score: implement exercise

config.json
I created the blurb here by starting with the first-sentence introduction on the Apache Groovy site, and attempting to winnow it down to 30 characters.
=> Fix #76 : Add blurb to config.json

CONTRIBUTING.md, config.json, exercises/two-fer/TwoFer.groovy
Just a couple minor fixes to existing config/code.
=> Minor fixes

config.json, exercises/triangle/Example.groovy, exercises/triangle/README.md, exercises/triangle/Triangle.groovy, exercises/triangle/TriangleSpec.groovy
Exercise implemented with tests and example solution.
Issue: #81
=> triangle: implement exercise

config.json, exercises/binary-search/BinarySearch.groovy, exercises/binary-search/BinarySearchSpec.groovy, exercises/binary-search/Example.groovy, exercises/binary-search/README.md
=> Implement exercise binary-search

exercises/linked-list/README.md
I just noticed that the README i submitted last week was referring to the wrong filename...sorry :(
=> Fixed a typo in the spec filename

exercises/bank-account/README.md, exercises/binary-search/README.md, exercises/flatten-array/README.md, exercises/gigasecond/README.md, exercises/grains/README.md, exercises/hamming/README.md, exercises/leap/README.md, exercises/phone-number/README.md, exercises/rna-transcription/README.md, exercises/roman-numerals/README.md, exercises/rotational-cipher/README.md, exercises/scrabble-score/README.md, exercises/triangle/README.md, exercises/two-fer/README.md, exercises/word-count/README.md
Update out-of-date READMEs using configlet.
=> Update READMEs using configlet

config.json, exercises/armstrong-numbers/ArmstrongNumbers.groovy, exercises/armstrong-numbers/ArmstrongNumbersSpec.groovy, exercises/armstrong-numbers/Example.groovy, exercises/armstrong-numbers/README.md
Hi, I'm not sure if everything is in the right format, but feel free to point out anything that needs to be updated!
=> Adds armstrong-numbers exercise

exercises/difference-of-squares/DifferenceOfSquares.groovy, exercises/difference-of-squares/DifferenceOfSquaresSpec.groovy, exercises/difference-of-squares/Example.groovy
In exercise "difference-of-squares", renamed `squareOfSums` to `squareOfSum`, as well as some instances of "sums" to "sum".
=> difference-of-squares: renamed squareOfSums to squareOfSum

config.json, exercises/matrix/Example.groovy, exercises/matrix/Matrix.groovy, exercises/matrix/MatrixSpec.groovy, exercises/matrix/README.md
This should fix issue #80 by implementing the matrix exercise.
=> Implemented the matrix exercise

config.json, exercises/difference-of-squares/README.md, exercises/grains/README.md, exercises/leap/README.md, exercises/matrix/README.md
I moved around a lot of the exercises and set many to `"core": true` matching the Java track as a template. Overall when the track is `active`, I think this will give a better experience to the users. Also, I set "hello-world" to be the first exercise for the core track, which should give a nice intro to Groovy for someone new.
=> Updates to core exercises

config.json, exercises/secret-handshake/Example.groovy, exercises/secret-handshake/README.md, exercises/secret-handshake/SecretHandshake.groovy, exercises/secret-handshake/SecretHandshakeSpec.groovy
This PR adds the secret handshake based off of work @m-a-ge started to close issue #79
=> Issue#79 add secret handshake

config.json, exercises/atbash-cipher/AtbashCipher.groovy, exercises/atbash-cipher/AtbashCipherSpec.groovy, exercises/atbash-cipher/Example.groovy, exercises/atbash-cipher/README.md
Hi, this PR is to add a new exercise for `atbash-cipher`, [here is a link to the problem-specifications](https://github.com/exercism/problem-specifications/tree/master/exercises/atbash-cipher)
Thanks!
=> Adds atbash-cipher exercise

config.json, exercises/resistor-color/Example.groovy, exercises/resistor-color/README.md, exercises/resistor-color/ResistorColor.groovy, exercises/resistor-color/ResistorColorSpec.groovy
Hi, this PR is to add a new exercise for `resistor-color`, [here is a link to the problem-specifications](https://github.com/exercism/problem-specifications/tree/master/exercises/resistor-color)
Thanks!
=> Adds resistor-color exercise

config.json, exercises/darts/Darts.groovy, exercises/darts/DartsSpec.groovy, exercises/darts/Example.groovy, exercises/darts/README.md
Hi, this PR is to add a new exercise for `darts `, [here is a link to the problem-specifications](https://github.com/exercism/problem-specifications/tree/master/exercises/darts)
=> Adds darts exercise

config.json, exercises/reverse-string/Example.groovy, exercises/reverse-string/README.md, exercises/reverse-string/ReverseString.groovy, exercises/reverse-string/ReverseStringSpec.groovy
Hi, this PR is to add a new exercise for `reverse-string`, [here is a link to the problem-specifications](https://github.com/exercism/problem-specifications/tree/master/exercises/reverse-string)
=> Adds reverse-string exercise

config.json, exercises/isogram/Example.groovy, exercises/isogram/Isogram.groovy, exercises/isogram/IsogramSpec.groovy, exercises/isogram/README.md
Hi, this PR is to add a new exercise for `isogram`, here is a link to the [problem-specifications](https://github.com/exercism/problem-specifications/tree/master/exercises/isogram)
=> Adds isogram exercise

config.json, exercises/allergies/Allergies.groovy, exercises/allergies/AllergiesSpec.groovy, exercises/allergies/Example.groovy, exercises/allergies/README.md
Hi, this PR is to add a new exercise for allergies, here is a link to the [problem-specifications](https://github.com/exercism/problem-specifications/tree/master/exercises/allergies)
=> Adds allergies exercise

config.json, exercises/armstrong-numbers/ArmstrongNumbersSpec.groovy, exercises/collatz-conjecture/CollatzConjecture.groovy, exercises/collatz-conjecture/CollatzConjectureSpec.groovy, exercises/collatz-conjecture/Example.groovy, exercises/collatz-conjecture/README.md
Hi, this PR is to add a new exercise for collatz-conjecture, here is a link to the [problem-specifications](https://github.com/exercism/problem-specifications/tree/master/exercises/collatz-conjecture)
=> Adds collatz-conjecture exercise

config.json
I think we are at a good spot to turn on the Groovy track, there already seems to be people doing the new exercises as they are being added. We have over all 38 exercises, and the core exercises seem to be all set. If anyone feels this needs more work before we turn this on, please post and let me know!
Thanks!
=> Set active to true

exercises/armstrong-numbers/.meta/src/reference/groovy/ArmstrongNumbers.groovy, exercises/armstrong-numbers/src/test/groovy/ArmstrongNumbersSpec.groovy
Update armstrong-numbers to v1.1.0 based on the new test case in [canonical-data.json](https://github.com/exercism/problem-specifications/blob/master/exercises/armstrong-numbers/canonical-data.json)
=> Updates to armstrong-numbers for v1.1.0

bin/create_exercise.groovy
Simple tool to help creating new exercise folders, should create folders based on the layout we have for our other exercises along with a `build.gradle` file.
=> Adds simple tool for creating new exercise folders

config.json, exercises/anagram/.meta/src/reference/groovy/Anagram.groovy, exercises/anagram/README.md, exercises/anagram/build.gradle, exercises/anagram/src/main/groovy/Anagram.groovy, exercises/anagram/src/test/groovy/AnagramSpec.groovy, exercises/settings.gradle
Hi, this PR is to add a new exercise for `anagram`, here is a link to the [problem-specifications](https://github.com/exercism/problem-specifications/tree/master/exercises/anagram)
=> Adds anagram exercise

config.json, exercises/acronym/.meta/src/reference/groovy/Acronym.groovy, exercises/acronym/README.md, exercises/acronym/build.gradle, exercises/acronym/src/main/groovy/Acronym.groovy, exercises/acronym/src/test/groovy/AcronymSpec.groovy, exercises/settings.gradle
Hi, this PR is to add a new exercise for `acronym`, here is a link to the [problem-specifications](https://github.com/exercism/problem-specifications/tree/master/exercises/acronym)
=> Adds acronym exercise

config.json, exercises/all-your-base/.meta/src/reference/groovy/AllYourBase.groovy, exercises/all-your-base/README.md, exercises/all-your-base/build.gradle, exercises/all-your-base/src/main/groovy/AllYourBase.groovy, exercises/all-your-base/src/test/groovy/AllYourBaseSpec.groovy, exercises/settings.gradle
Hi, this PR is to add a new exercise for `all-your-base`, here is a link to the [problem-specifications](https://github.com/exercism/problem-specifications/tree/master/exercises/all-your-base)
=> Adds all-your-base exercise

exercises/flatten-array/src/main/groovy/FlattenArray.groovy
This should close out #184, the only stub file missing was for FlattenArray.
=> Closes #184 by adding stub for FlattenArray

gradle/wrapper/gradle-wrapper.properties, gradlew, gradlew.bat
This Pull updates Gradle to v5.6.2.
=> Upgrade Gradle to v5.6.2

.github/workflows/configlet.yml, .github/workflows/gradle-wrapper-validation.yml
Testing Github Workflows,
- Adding one the "configlet" task to ensure things for formatted right
- Adding one for "Validate Gradle Wrapper", https://blog.gradle.org/gradle-wrapper-checksum-verification-github-action
=> Add Github Workflows

config.json
This PR is to update the `config.json` to use topics found in the [TOPICS.txt](https://github.com/exercism/problem-specifications/blob/master/TOPICS.txt) from the `problem-specifications` repo
=> Update topics to match ones from TOPICS.txt

exercises/practice/hello-world/src/main/groovy/HelloWorld.groovy
Simplify the `hello-world` exercise's stub. The goal of this is to make things easier for students to get started and to introduce as little syntax as possible.
See https://github.com/exercism/v3-launch/issues/46
=> 🤖 Simplify `hello-world` stub

README.md, config.json
Following [Groovy official website](https://groovy-lang.org/).
=> Key features

exercises/practice/bob/.docs/instructions.md, exercises/practice/bob/.docs/introduction.md, exercises/practice/darts/.docs/instructions.md, exercises/practice/etl/.meta/config.json, exercises/practice/gigasecond/.docs/introduction.md, exercises/practice/linked-list/.docs/instructions.md, exercises/practice/matching-brackets/.docs/instructions.md, exercises/practice/pangram/.docs/instructions.md, exercises/practice/pangram/.docs/introduction.md, exercises/practice/resistor-color-trio/.docs/instructions.md, exercises/practice/roman-numerals/.docs/instructions.md, exercises/practice/saddle-points/.docs/instructions.md, exercises/practice/saddle-points/.docs/introduction.md, exercises/practice/secret-handshake/.docs/instructions.md, exercises/practice/secret-handshake/.meta/config.json, exercises/practice/space-age/.docs/instructions.md, exercises/practice/two-fer/.docs/instructions.md
The results of running `./bin/configlet sync --docs --filepaths --metadata -uy`
=> Sync exercise files and metadata

config.json
=> Sort exercises by binned difficulty

exercises/practice/accumulate/.meta/config.json, exercises/practice/acronym/.docs/instructions.md, exercises/practice/all-your-base/.docs/instructions.md, exercises/practice/allergies/.docs/instructions.md, exercises/practice/armstrong-numbers/.docs/instructions.md, exercises/practice/binary-search/.docs/instructions.md, exercises/practice/darts/.docs/instructions.md, exercises/practice/hello-world/.meta/config.json, exercises/practice/isogram/.docs/instructions.md, exercises/practice/leap/.docs/instructions.md, exercises/practice/leap/.docs/introduction.md, exercises/practice/leap/.meta/config.json, exercises/practice/perfect-numbers/.docs/instructions.md, exercises/practice/phone-number/.docs/instructions.md, exercises/practice/protein-translation/.docs/instructions.md, exercises/practice/queen-attack/.docs/instructions.md, exercises/practice/rotational-cipher/.docs/instructions.md, exercises/practice/series/.docs/instructions.md, exercises/practice/strain/.meta/config.json
=> Run `configlet sync --metadata --docs`

exercises/practice/strain/.meta/config.json, exercises/practice/strain/.meta/tests.toml, exercises/practice/strain/src/test/groovy/StrainSpec.groovy
@ErikSchierboom, I noticed the strain tests.toml was missing, and that led me to noticing the tests weren't fully synced anyways. I also synced the metadata while I was in there.
=> Update strain test suite

.github/workflows/gradle-build.yml, exercises/practice/darts/.docs/instructions.md, exercises/practice/darts/.meta/config.json, exercises/practice/flatten-array/.docs/instructions.md, exercises/practice/matching-brackets/.docs/instructions.md, exercises/practice/matching-brackets/.docs/introduction.md, exercises/practice/raindrops/.meta/config.json, exercises/practice/space-age/.docs/instructions.md, exercises/practice/space-age/.docs/introduction.md
This is docs and metadata.
There are 29 exercises needing synced tests: I'm not up for that just now.
=> Sync with recent probspec changes
