exercism/groovy

config.json, docs/ABOUT.md, docs/INSTALLATION.md, docs/LEARNING.md, docs/RESOURCES.md, docs/TESTS.md
Includes all necessary markdown to flesh out the Groovy language exercism docs.
Used the existing documentation for Elixir for reference, but splashed into the Java docs since Groovy requires it as an installation dependency.
=> Groovy documentation

exercises/raindrops/RaindropsTest.groovy
By using simple Groovy assertions, we
- remove references to JUnit, which may confuse non-Java folk
- make the tests fit onto a single page, improving readability
- use Groovy's native power `assert`, making the tests more idiomatic
- remove the need to comment/ignore tests to practice TDD
(the first test to fail outputs and halts)
But the primary motivator for me was to make the output clearer.
The second failure under JUnit tests reads something like:
```
] groovy RaindropsTest.groovy
JUnit 4 Runner, Tests: 16, Failures: 13, Time: 59
Test Failure: test105(RaindropsTest)
org.junit.ComparisonFailure: expected:<[PlingPlangPlong]> but was:<[105]>
at org.junit.Assert.assertEquals(Assert.java:115)
at org.junit.Assert.assertEquals(Assert.java:144)
```
...several dozen stacktrace lines, which …
=> Simplify Raindrops tests

LICENSE
Per issue #41 , the project was missing a license file.  This Pull takes the license from the `xruby` project.
=> Add MIT open source license file

config/exercise_readme.go.tmpl, exercises/difference-of-squares/README.md, exercises/gigasecond/README.md, exercises/grains/README.md, exercises/hamming/README.md, exercises/hello-world/README.md, exercises/leap/README.md, exercises/nth-prime/README.md, exercises/phone-number/README.md, exercises/raindrops/README.md, exercises/rna-transcription/README.md, exercises/robot-name/README.md, exercises/roman-numerals/README.md, exercises/word-count/README.md
We are working towards making exercises stand-alone. That is to say: no more generating READMEs on the fly.
This will give maintainers more control over each individual exercise README, and it will also make some of the backend logic for delivering exercises simpler.
The README template uses the Go text/template package, and the default templates generate the same READMEs as we have been generating on the fly.  See the documentation in [regenerating exercise readmes][regenerate-docs] for details.
The READMEs can be generated at any time using a new 'generate' command in configlet. This command has not yet landed in master or been released, but can be built from source in the generate-readmes branch on [configlet][].
[configlet]: https://github.com/exercism/configlet
[regenerate-docs]: …
=> Generate static exercise README templates

config.json, exercises/linked-list/DoubleLinkedList.groovy, exercises/linked-list/DoubleLinkedListSpec.groovy, exercises/linked-list/Example.groovy, exercises/linked-list/README.md
This should fix issue #85 by adding the `linked-list` exercise.
The README.md file, the tests and the example implementation have been ported and adapted from  [the Java version](https://github.com/exercism/java/tree/master/exercises/linked-list); where applicable, I tried to be as groovy-idiomatic as I could.
=> Ported the linked-list exercise from java

exercises/phone-number/Example.groovy, exercises/phone-number/PhoneNumber.groovy, exercises/phone-number/PhoneNumberSpec.groovy, exercises/phone-number/README.md
Add tests to disallow 0 and 1 as first digit of area code or exchange
and update example to pass new tests. Also, fix typo in README.md.
Resolves #110
=> phone-number: Update tests to match problem specs

exercises/gigasecond/GigasecondSpec.groovy
Some time zones that use Daylight Saving Time caused the tests
to fail even though the requirement was met.  To fix the tests
to work regardless of the machine's local time zone, force the
dates used in the test to be written in UTC.
This should fix #105
=> gigasecond: Make tests valid regardless of local time zone

docs/INSTALLATION.md
The present link for sdkman install instructions seems to be outdated and nonfunctional, so this simply updates it to a working url.
=> fix: update link to sdkman install guide

exercises/robot-name/src/test/groovy/RobotNameSpec.groovy
Here we allowed a lowercase name.
Star Wars would get silly if you had C3P0 and c3p0
=> Robot name is uppercase in the specification.

gradle/wrapper/gradle-wrapper.properties
Upgrades the Gradle Wrapper used for CI to 5.6.4
https://docs.gradle.org/5.6.4/release-notes.html
=> Upgrade Gradle to 5.6.4

exercises/high-scores/.meta/src/reference/groovy/HighScores.groovy, exercises/high-scores/src/test/groovy/HighScoresSpec.groovy
Add test to ensure the sorting in personalTopThree does not mutate the instance variable containing the list of scores.
=> high-scores: new test for non-mutating personalTopThree

CONTRIBUTING.md, docs/ABOUT.md, docs/LEARNING.md, docs/TESTS.md
We've defined a [specification for Markdown files](https://github.com/exercism/docs/blob/main/contributing/standards/markdown.md) to be applied Exercism-wide. This standard includes, amongst others, the following two rules:
- All files must start start with a level-1 heading (`# Some heading text`)
- No heading may decend a level greater than one below the previous (e.g. `## may only be followed by ###, not ####`)
This PR applies the above two rules to the Markdown documents in this repo. 
https://github.com/exercism/v3-launch/issues/17
=> [v3] Update Markdown files to latest spec

exercises/practice/etl/.meta/config.json, exercises/practice/linked-list/.meta/config.json
In this PR, we created (empty) stub files for all exercises that didn't yet have them.
The lack of stub file generates an unnecessary pain point within Exercism, contributing a significant proportion of support requests, making things more complex for our students, and hindering our ability to automatically run test-suites and provide automated analysis of solutions.
The original discussion for this is at exercism/discussions#238.
**We will automatically merge this PR in two week's time if it has not been merged by track maintainers at that point :slightly_smiling_face:**
https://github.com/exercism/v3-launch/issues/33
=> 🤖 Add stub files to all exercises

exercises/practice/luhn/src/test/groovy/LuhnSpec.groovy
For the test runner to [import `@Stepwise`](https://github.com/exercism/groovy-test-runner/blob/2c52ac9872321bc1bfc06896ed0658c2becb865f/bin/run.sh#L43) successfully and avoid this error:
```
[ERROR] /mnt/exercism-iteration/src/test/groovy/LuhnSpec.groovy: 4: unable to resolve class Stepwise for annotation
[ERROR]  @ line 4, column 1.
[ERROR]    @Stepwise
[ERROR]    ^
[ERROR] 1 error
```
=> Import Spock classes with a wildcard 

exercises/practice/gigasecond/.docs/introduction.md, exercises/practice/linked-list/.docs/instructions.md, exercises/practice/pangram/.docs/introduction.md
In line with Exercism's spec, we're ensuring that all admonition fences are demarcated with four tildes (`~~~~`) across all repositories. We will be following up with an org-wide script that can be used to keep this consistent. [Problem Specifications](https://github.com/exercism/problem-specifications) has already been updated.
We'll automatically merge this a week from now, but feel free to merge beforehand!
- Spec: https://exercism.org/docs/building/markdown/markdown#h-special-blocks-sometimes-called-admonitions
- Meta issue: https://github.com/exercism/exercism/issues/6705
=> Convert backtick (`) admonition fences to tildes (~)

.github/workflows/gradle-build.yml
This PR updates GitHub Actions runners to a specific version.
This ensures that the workflow will always run on the same runner, which makes your build _stable_.
The PR updates the *-latest version with the current version, as specified in https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources.
See https://exercism.org/docs/building/github/gha-best-practices#h-pin-test-runners-to-version for more information.
=> CI: pin GitHub Actions runners

.github/workflows/gradle-build.yml
This PR updates GitHub Actions workflows to a specific version.
This ensures that the workflow will always run the same code, which makes your build _stable_.
It will also prevent a potential security issue where a tag could be replaced by a malicious commit without consumers being aware of it.
The PR updates each non-SHA based workflow reference with the SHA of the referenced version/tag, so the current behavior should not change.
See https://exercism.org/docs/building/github/gha-best-practices#h-pin-actions-to-shas for more information.
=> CI: pin GitHub Actions workflows

exercises/practice/queen-attack/.meta/config.json
`exercism submit` (with no args) only picks up one.
=> queen-attack solution requires two files

exercises/practice/all-your-base/src/test/groovy/AllYourBaseSpec.groovy
The "Input base 0" test case was incorrectly supplying 1 as input base, this change fixes it.
=> Fix bug in all-your-base test

.github/workflows/gradle-build.yml
Suggested by [the gradle/wrapper-validation-action v3.5.0 release notes](https://github.com/gradle/wrapper-validation-action/releases/tag/v3.5.0). 
The SHA for "gradle/actions/wrapper-validation@v3" [is here](https://github.com/gradle/actions/releases/tag/v3.5.0).
=> Replace gradle/wrapper-validation-action with gradle/actions/wrapper-validation

exercises/practice/largest-series-product/.meta/src/reference/groovy/LargestSeriesProduct.groovy, exercises/practice/largest-series-product/src/main/groovy/LargestSeriesProduct.groovy
Rename the `Exercise` class to `LargestSeriesProduct` (matches the file name and the class name expected by the tests):
- in the stub file
- in reference solution
=> [largest-series-product] Align class and file names

exercises/practice/robot-simulator/.docs/instructions.append.md, exercises/practice/robot-simulator/.docs/instructions.md, exercises/practice/robot-simulator/.meta/src/reference/groovy/RobotSimulator.groovy, exercises/practice/robot-simulator/src/main/groovy/RobotSimulator.groovy, exercises/practice/robot-simulator/src/test/groovy/RobotSimulatorSpec.groovy
- verify results properties through getters
- make code groovier (use def key-word, remove semi-colons)
- use Spock's given/when/then
- visually separate parts of data-driven test inputs
- document Groovy's values and properties
Follow entire discussion on the original PR: https://github.com/artamonovkirill/groovy/pull/1
=> Refactor robot-simulator exercise

exercises/practice/robot-simulator/src/test/groovy/RobotSimulatorSpec.groovy
Fixes "src/test/groovy/RobotSimulatorSpec.groovy: 5: unable to resolve class Stepwise for annotation":
Since groovy-test-running imports Stepwise annotation, a wild-card or `spock.lang.Stepwise` import is required.
Opted for a wild-card option as this is how it was prior to https://github.com/exercism/groovy/pull/461
=> Fix robot-simulator tests in groovy-test-runner
